from .MainView import *
from .ProductListView import *
from .SearchBookInManageView import *
from .ProductDeleteView import *
from .ProductModifyView import *
from .AjaxGetProductInfoView import *
from .ProductRegisterView import *
from .SearchBookAjaxView import *
from .BookRegisterView import *
