# Generated by Django 3.0.5 on 2020-10-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0002_auto_20201006_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
