# Generated by Django 3.0.5 on 2020-10-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0003_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
