# Generated by Django 3.0.1 on 2020-05-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200512_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img_src',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_msg',
        ),
    ]
